allowBuilds:
  '@fhenixprotocol/cofhe-contracts': false
  '@reown/appkit': false
  better-sqlite3: true
  bufferutil: true
  esbuild: true
  keccak: true
  utf-8-validate: true
minimumReleaseAgeExclude:
  - '@aws-sdk/client-kms@3.1132.0'
